### ISSUE TITLE
start tagging releases

### ISSUE THREAD

**Issue by stopfstedt** [ucsf-ckm/moodle-theme-ucsf#6]
since this project will see increased activity in the foreseeable future, let's stop [deploying](https://github.com/ucsf-ckm/moodle/blob/UCSFCLE_27_STABLE/.gitmodules#L91) off the `HEAD` of this repo's `master`.

@ctam let's discuss version naming conventions.

**Comment by ctam** [comment]
Since this is a moodle project, I would recommend following the Moodle conventions.

**Comment by stopfstedt** [comment]
as discussed, it turns out that moodle versioning conventions do not apply, since our release cycle is not primarily tied to theirs. 
no reason fall into lockstep with moodle/core.

instead, let's go with basic [semantic versioning](http://semver.org/). 
i tagged whatever is in production right now as version `1.0.0`.
